fixtures:
  forge_modules:
    stdlib:          "puppetlabs/stdlib"
    artifactory:     "autostructure/artifactory"
    artifactory_pro: "autostructure/artifactory_pro"
    wget:            "maestrodev/wget"
  symlinks:
    artifactory_ha: "#{source_dir}"
